// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVQQQUQ0MdKryNNDzyjqb6R0rTqOjrAzg',
    appId: '1:557373584822:web:af8e73629635ff9acdfd17',
    messagingSenderId: '557373584822',
    projectId: 'vapestore-6a7f1',
    authDomain: 'vapestore-6a7f1.firebaseapp.com',
    storageBucket: 'vapestore-6a7f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGlKZTAikY3i6BYvo3EkVubRo90DO6Zc',
    appId: '1:557373584822:android:cedc4a272b7b1708cdfd17',
    messagingSenderId: '557373584822',
    projectId: 'vapestore-6a7f1',
    storageBucket: 'vapestore-6a7f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlzUXkc9VIhAiZC6S2oWFTiCyjc--9etk',
    appId: '1:557373584822:ios:eb5a53b768986b7acdfd17',
    messagingSenderId: '557373584822',
    projectId: 'vapestore-6a7f1',
    storageBucket: 'vapestore-6a7f1.appspot.com',
    iosBundleId: 'com.example.vapestoreProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlzUXkc9VIhAiZC6S2oWFTiCyjc--9etk',
    appId: '1:557373584822:ios:eb5a53b768986b7acdfd17',
    messagingSenderId: '557373584822',
    projectId: 'vapestore-6a7f1',
    storageBucket: 'vapestore-6a7f1.appspot.com',
    iosBundleId: 'com.example.vapestoreProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVQQQUQ0MdKryNNDzyjqb6R0rTqOjrAzg',
    appId: '1:557373584822:web:bc111d1a75413abfcdfd17',
    messagingSenderId: '557373584822',
    projectId: 'vapestore-6a7f1',
    authDomain: 'vapestore-6a7f1.firebaseapp.com',
    storageBucket: 'vapestore-6a7f1.appspot.com',
  );

}